version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    image: lighthouse-inspector/web
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "8081:3000"

  runner:
    image: lighthouse-inspector/runner
    build:
      dockerfile: ./cron.Dockerfile
    volumes:
      - ./:/usr/src/app
