version: "3.9"
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9010:9000"
      - "9011:9001"
    volumes:
      - ./minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data

  app:
    depends_on:
      - database
      - minio
    image: faebeee/web-audit-web
    build:
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/lhi
      - NEXTAUTH_URL=http://0.0.0.0:3003
      - MINIO_HOST=minio
      - MINIO_BUCKET=lighthouse-report
      - MINIO_ACCESS_KEY=zwX1TeYJGdVRpW4a
      - MINIO_SECRET_KEY=OsF3XMHMYkeP4QRRHLbXPoPWeuQ9mBD1
      - NEXTAUTH_SECRET=mBBB7M61VJBU5VaYCW54g439JERbtH4Ge61j
    ports:
      - "3003:3000"


  cron:
    depends_on:
      - database
      - minio
    image: faebeee/web-audit-cron
    build:
      dockerfile: ./docker/cron/Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://doadmin:AVNS_BrEZ-uTH32RTBX7aZ_a@db-postgresql-fra1-09806-do-user-2359801-0.b.db.ondigitalocean.com:25060/dev?sslmode=require
      - MINIO_HOST=159.223.249.139
      - MINIO_PORT=9000
      - MINIO_BUCKET=web-audit
      - MINIO_ACCESS_KEY=bLLH6w4lfxlFSIDH
      - MINIO_SECRET_KEY=gVNRWqz7hzkhD0Lcr5qCJPO8pyMuWK2E
