version: "3.9"
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data

  app:
    depends_on:
      - database
      - minio
    image: lighthouse-inspector/web
    build:
      dockerfile: ./Dockerfile
      args:
        - DATABASE_URL=postgresql://postgres:postgres@database:5432/lhi
        - MINIO_HOST=minio
        - MINIO_BUCKET=lighthouse-report
        - MINIO_ACCESS_KEY=zwX1TeYJGdVRpW4a
        - MINIO_SECRET_KEY=OsF3XMHMYkeP4QRRHLbXPoPWeuQ9mBD1
    volumes:
      - ./:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/lhi
      - MINIO_HOST=minio
      - MINIO_BUCKET=lighthouse-report
      - MINIO_ACCESS_KEY=zwX1TeYJGdVRpW4a
      - MINIO_SECRET_KEY=OsF3XMHMYkeP4QRRHLbXPoPWeuQ9mBD1
      - NEXTAUTH_SECRET=mBBB7M61VJBU5VaYCW54g439JERbtH4Ge61j
    ports:
      - "3000:3000"


  cron:
    depends_on:
      - database
      - minio
    image: lighthouse-inspector/cron
    build:
      dockerfile: ./cron.Dockerfile
      args:
        - DATABASE_URL=postgresql://postgres:postgres@database:5432/lhi
        - MINIO_HOST=minio
        - MINIO_BUCKET=lighthouse-report
        - MINIO_ACCESS_KEY=zwX1TeYJGdVRpW4a
        - MINIO_SECRET_KEY=OsF3XMHMYkeP4QRRHLbXPoPWeuQ9mBD1
    volumes:
      - ./:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/lhi
      - MINIO_HOST=minio
      - MINIO_BUCKET=lighthouse-report
      - MINIO_ACCESS_KEY=zwX1TeYJGdVRpW4a
      - MINIO_SECRET_KEY=OsF3XMHMYkeP4QRRHLbXPoPWeuQ9mBD1

